//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HijriCalendar {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HijriCalendar.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutCaption {
            get {
                return ResourceManager.GetString("AboutCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2012 Ahmad Masykur. For more information please see www.masykur.web.id or email ahmad@masykur.web.id.
        /// </summary>
        public static string AboutMessage {
            get {
                return ResourceManager.GetString("AboutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dhu al-Hijja.
        /// </summary>
        public static string DhulHijjah {
            get {
                return ResourceManager.GetString("DhulHijjah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dhu al-Qa&apos;da.
        /// </summary>
        public static string DhulQoidah {
            get {
                return ResourceManager.GetString("DhulQoidah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jumada ath-Thaniya.
        /// </summary>
        public static string JumadilAkhir {
            get {
                return ResourceManager.GetString("JumadilAkhir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jumada al-Ula.
        /// </summary>
        public static string JumadilAwal {
            get {
                return ResourceManager.GetString("JumadilAwal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muharram.
        /// </summary>
        public static string Muḥarram {
            get {
                return ResourceManager.GetString("Muḥarram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rabi ath-Thani.
        /// </summary>
        public static string RabiilAkhir {
            get {
                return ResourceManager.GetString("RabiilAkhir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rabi al-Awwal.
        /// </summary>
        public static string RabiilAwal {
            get {
                return ResourceManager.GetString("RabiilAwal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rajab.
        /// </summary>
        public static string Rajab {
            get {
                return ResourceManager.GetString("Rajab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ramadan.
        /// </summary>
        public static string Ramadhan {
            get {
                return ResourceManager.GetString("Ramadhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sha&apos;ban.
        /// </summary>
        public static string Saban {
            get {
                return ResourceManager.GetString("Saban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safar.
        /// </summary>
        public static string Safar {
            get {
                return ResourceManager.GetString("Safar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shawwal.
        /// </summary>
        public static string Shawwal {
            get {
                return ResourceManager.GetString("Shawwal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
    }
}
